# == AUTOGENERATED MODULE REGISTRY ==
# Do not edit manually. Run: python utils/autoregistrar.py
AUTO_MODULES = ['ai_backends', 'app_module', 'automation_module', 'context_location_proximity_identity_detector_v2', 'context_video_vs_real_detector', 'criminal_behavior_patterns', 'device_analyzer_module', 'enhance_module', 'extortion_analyzer', 'face_recognition_module', 'fraud_detection_module', 'identity_spoofing_detector', 'interaction_module', 'knowledge_engine', 'learning_module', 'media_module', 'memory_module', 'optimizer_module', 'render_module', 'secure_communication', 'swapface_module', 'swapface_video_gender_blend', 'system_module', 'threat_analyzer', 'voice_module', 'webremote_module']
# == END REGISTRY ==
