FROM python:3.11-slim

WORKDIR /app

RUN apt-get update && apt-get install -y --no-install-recommends \
    iproute2 net-tools iptables && \
    rm -rf /var/lib/apt/lists/*

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY CORE_SHARED/ CORE_SHARED/
COPY JOSAMICK/ JOSAMICK/
COPY .env .env

EXPOSE 5001

ENV PYTHONUNBUFFERED=1

CMD ["python", "JOSAMICK/server.py"]
