import os

MODULES_DIR = "modules"
REGISTRY_FILE = os.path.join(MODULES_DIR, "_registry.py")

def get_module_names():
    return sorted([
        f[:-3] for f in os.listdir(MODULES_DIR)
        if f.endswith(".py")
        and not f.startswith("__")
        and not f.startswith("test")
        and f != "_registry.py"
    ])

def generate_registry():
    mods = get_module_names()
    content = "# == AUTOGENERATED MODULE REGISTRY ==\n"
    content += "# Do not edit manually. Run: python utils/autoregistrar.py\n"
    content += f"AUTO_MODULES = {repr(mods)}\n"
    content += "# == END REGISTRY ==\n"

    with open(REGISTRY_FILE, "w", encoding="utf-8") as f:
        f.write(content)

    print(f"[AUTOREG] Registro actualizado: {len(mods)} modulos")
    return mods

if __name__ == "__main__":
    generate_registry()
